using UnityEngine;
using System.Collections;
using PureMVC.Patterns;
using PureMVC.Interfaces;
/// <summary>
/// Auto Generated By ZJRTool, Do Not Modify
/// </summary>
public class ReadDataBaseCommand : SimpleCommand
{
    public override void Execute(INotification notification)
    {
        DbAccess dbAccess = new DbAccess(DbAccess.dbStatname);
        sqlite_sequence.GetInstance().ReadData(dbAccess);
        system_catgroup.GetInstance().ReadData(dbAccess);
        system_basedata.GetInstance().ReadData(dbAccess);
        stat_squareset.GetInstance().ReadData(dbAccess);
        stat_skillsp.GetInstance().ReadData(dbAccess);
        stat_missionpatterns.GetInstance().ReadData(dbAccess);
        stat_buildingsp.GetInstance().ReadData(dbAccess);
        stat_blueprint.GetInstance().ReadData(dbAccess);
        stat_levelstat.GetInstance().ReadData(dbAccess);
        stat_skill.GetInstance().ReadData(dbAccess);
        stat_series.GetInstance().ReadData(dbAccess);
        stat_building.GetInstance().ReadData(dbAccess);
        system_bgm.GetInstance().ReadData(dbAccess);
        stat_cat.GetInstance().ReadData(dbAccess);
        dbAccess.CloseSqlConnection();
    }
}
