using System.Collections.Generic;
public class sqlite_sequenceRow
{
    public string name;
    public string seq;
}
/// <summary>
/// Auto Generated By ZJRTool, Do Not Modify
/// </summary>
public class sqlite_sequence : DatabaseSerializer
{
    private static sqlite_sequence mInstance;
    public List<sqlite_sequenceRow> rowList = new List<sqlite_sequenceRow>();
    public static sqlite_sequence GetInstance()
    {
        return mInstance ?? (mInstance = new sqlite_sequence());
    }
    protected override void AddRow(object[] rowInfo)
    {
        sqlite_sequenceRow row = new sqlite_sequenceRow();
        row.name = GetString(rowInfo[0]);
        row.seq = GetString(rowInfo[1]);
        rowList.Add(row);
    }
}
