using System.Collections.Generic;
public class stat_levelstatRow
{
    public int id;
    public string name;
    public int needpoint;
}
/// <summary>
/// Auto Generated By ZJRTool, Do Not Modify
/// </summary>
public class stat_levelstat : DatabaseSerializer
{
    private static stat_levelstat mInstance;
    public List<stat_levelstatRow> rowList = new List<stat_levelstatRow>();
    public static stat_levelstat GetInstance()
    {
        return mInstance ?? (mInstance = new stat_levelstat());
    }
    protected override void AddRow(object[] rowInfo)
    {
        stat_levelstatRow row = new stat_levelstatRow();
        row.id = GetInt(rowInfo[0]);
        row.name = GetString(rowInfo[1]);
        row.needpoint = GetInt(rowInfo[2]);
        rowList.Add(row);
    }
}
