using System.Collections.Generic;
public class stat_buildingspRow
{
    public int id;
}
/// <summary>
/// Auto Generated By ZJRTool, Do Not Modify
/// </summary>
public class stat_buildingsp : DatabaseSerializer
{
    private static stat_buildingsp mInstance;
    public List<stat_buildingspRow> rowList = new List<stat_buildingspRow>();
    public static stat_buildingsp GetInstance()
    {
        return mInstance ?? (mInstance = new stat_buildingsp());
    }
    protected override void AddRow(object[] rowInfo)
    {
        stat_buildingspRow row = new stat_buildingspRow();
        row.id = GetInt(rowInfo[0]);
        rowList.Add(row);
    }
}
