using System.Collections.Generic;
public class stat_skillspRow
{
    public int id;
}
/// <summary>
/// Auto Generated By ZJRTool, Do Not Modify
/// </summary>
public class stat_skillsp : DatabaseSerializer
{
    private static stat_skillsp mInstance;
    public List<stat_skillspRow> rowList = new List<stat_skillspRow>();
    public static stat_skillsp GetInstance()
    {
        return mInstance ?? (mInstance = new stat_skillsp());
    }
    protected override void AddRow(object[] rowInfo)
    {
        stat_skillspRow row = new stat_skillspRow();
        row.id = GetInt(rowInfo[0]);
        rowList.Add(row);
    }
}
