using System.Collections.Generic;
public class stat_blueprintRow
{
    public int id;
    public int type;
    public string name;
    public string description;
    public int pointto;
    public int cost_exp;
    public int cost_diamond;
    public int weekday;
    public int timegap;
}
/// <summary>
/// Auto Generated By ZJRTool, Do Not Modify
/// </summary>
public class stat_blueprint : DatabaseSerializer
{
    private static stat_blueprint mInstance;
    public List<stat_blueprintRow> rowList = new List<stat_blueprintRow>();
    public static stat_blueprint GetInstance()
    {
        return mInstance ?? (mInstance = new stat_blueprint());
    }
    protected override void AddRow(object[] rowInfo)
    {
        stat_blueprintRow row = new stat_blueprintRow();
        row.id = GetInt(rowInfo[0]);
        row.type = GetInt(rowInfo[1]);
        row.name = GetString(rowInfo[2]);
        row.description = GetString(rowInfo[3]);
        row.pointto = GetInt(rowInfo[4]);
        row.cost_exp = GetInt(rowInfo[5]);
        row.cost_diamond = GetInt(rowInfo[6]);
        row.weekday = GetInt(rowInfo[7]);
        row.timegap = GetInt(rowInfo[8]);
        rowList.Add(row);
    }
}
