using System.Collections.Generic;
public class system_basedataRow
{
    public float curentversion;
    public int userid;
}
/// <summary>
/// Auto Generated By ZJRTool, Do Not Modify
/// </summary>
public class system_basedata : DatabaseSerializer
{
    private static system_basedata mInstance;
    public List<system_basedataRow> rowList = new List<system_basedataRow>();
    public static system_basedata GetInstance()
    {
        return mInstance ?? (mInstance = new system_basedata());
    }
    protected override void AddRow(object[] rowInfo)
    {
        system_basedataRow row = new system_basedataRow();
        row.curentversion = GetFloat(rowInfo[0]);
        row.userid = GetInt(rowInfo[1]);
        rowList.Add(row);
    }
}
