using System.Collections.Generic;
public class system_bgmRow
{
    public int id;
    public string scene;
    public string status;
    public string track;
}
/// <summary>
/// Auto Generated By ZJRTool, Do Not Modify
/// </summary>
public class system_bgm : DatabaseSerializer
{
    private static system_bgm mInstance;
    public List<system_bgmRow> rowList = new List<system_bgmRow>();
    public static system_bgm GetInstance()
    {
        return mInstance ?? (mInstance = new system_bgm());
    }
    protected override void AddRow(object[] rowInfo)
    {
        system_bgmRow row = new system_bgmRow();
        row.id = GetInt(rowInfo[0]);
        row.scene = GetString(rowInfo[1]);
        row.status = GetString(rowInfo[2]);
        row.track = GetString(rowInfo[3]);
        rowList.Add(row);
    }
}
